#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("blocke.waitingdots.Resource", IsApplication=false)]

namespace blocke.waitingdots
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public static int autoplay = 2130771971;
			
			// aapt resource value: 0x7f010000
			public static int dotsColor = 2130771968;
			
			// aapt resource value: 0x7f010002
			public static int jumpHeight = 2130771970;
			
			// aapt resource value: 0x7f010001
			public static int period = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f030000
			public static int dot1 = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int dot2 = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int dot3 = 2130903042;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public static int dots_text_view = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] WaitingDots = new int[] {
					16842901,
					16842904,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public static int WaitingDots_android_textColor = 1;
			
			// aapt resource value: 0
			public static int WaitingDots_android_textSize = 0;
			
			// aapt resource value: 5
			public static int WaitingDots_autoplay = 5;
			
			// aapt resource value: 2
			public static int WaitingDots_dotsColor = 2;
			
			// aapt resource value: 4
			public static int WaitingDots_jumpHeight = 4;
			
			// aapt resource value: 3
			public static int WaitingDots_period = 3;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
